### ISSUE TITLE
Version mismatched

### ISSUE THREAD

**Issue by favoyang** [elraccoone/unity-nest-utilities-client#1]
**Describe the bug**

- Git tag: 1.1.2
- package.json version: 1.1.0 (should be 1.1.2)

To fix:
- Easier: bump the version to 1.1.3 and create new Git tag 1.1.3
- Or, bump the version to 1.1.2 and re-create Git tag 1.1.2

Refs: https://openupm.com/packages/nl.elraccoone.nest-utilities-client/?subPage=pipelines

**Comment by jeffreylanters** [comment]
Hi @favoyang, thanks for the issue. I've decided to push a new tag. 1.1.3 is up!
